---
abstract: 'A Chinese IRC server base on Mojolicious'
author:
  - 'sjdy521 <sjdy521@163.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.1, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojo-IRC-Server-Chinese
no_index:
  directory:
    - t
    - inc
requires:
  Encode::Locale: '1.05'
  Mojolicious: '6.11'
  Parse::IRC: '1.20'
resources:
  repository: git://github.com/sjdy521/Mojo-IRC-Server-Chinese.git
version: v1.8.1
x_serialization_backend: 'CPAN::Meta::YAML version 0.016'
