---
abstract: 'Basic HTTP Auth Helper Plus'
author:
  - 'Brad Robertson <blr@cpan.org>'
build_requires:
  Mojo::ByteStream: '0'
  Mojo::IOLoop: '0'
  Mojolicious::Lite: '0'
  Test::Mojo: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.24, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-BasicAuthPlus
no_index:
  directory:
    - t
    - inc
requires:
  Authen::Simple::Passwd: '0'
  Authen::Simple::Password: '0'
  Mojolicious: '1.4'
  Net::LDAP: '0'
  Test::More: '0'
  perl: '5.006001'
resources:
  bugtracker: http://github.com/stregone/mojolicious-plugin-basicauthplus/issues
  repository: http://github.com/stregone/mojolicious-plugin-basicauthplus
version: v0.11.1
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
