---
abstract: 'Use XS JSON with Mojolicious'
author:
  - 'Nic Sandfield <niczero@cpan.org>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.3'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.24, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojo-JSON_XS
no_index:
  directory:
    - t
    - inc
    - data
    - test
requires:
  Cpanel::JSON::XS: '3.0109'
  Mojolicious: '5.66'
  perl: '5.010001'
resources:
  bugtracker: http://github.com/niczero/mojo-jsonxs/issues
  homepage: http://niczero.github.io/mojo-jsonxs
  license: http://www.opensource.org/licenses/artistic-license-2.0
  repository: http://github.com/niczero/mojo-jsonxs
version: 1.003
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
