---
abstract: "Mojolicious â\x9D¤ï¸\x8F Reveal.js"
author:
  - 'Joel Berger, E<lt>joel.a.berger@gmail.comE<gt>'
build_requires: {}
configure_requires:
  Module::Build::Tiny: '0.034'
dynamic_config: 0
generated_by: 'App::ModuleBuildTiny version 0.018, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-RevealJS
provides:
  Mojolicious::Plugin::RevealJS:
    file: lib/Mojolicious/Plugin/RevealJS.pm
    version: '0.12'
requires:
  File::Share: '0'
  Mojolicious: '7.15'
  perl: v5.12.0
resources:
  bugtracker: http://github.com/jberger/Mojolicious-Plugin-RevealJS/issues
  license: http://dev.perl.org/licenses/
  repository: http://github.com/jberger/Mojolicious-Plugin-RevealJS
version: '0.12'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
