---
abstract: 'Perlish Configuration for Mojolicious, with merging of deeply-nested defaults'
author:
  - 'Dotan Dimet <dotan@corky.net>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.18, CPAN::Meta::Converter version 2.150005'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-ConfigHashMerge
no_index:
  directory:
    - t
    - inc
    - t
requires:
  Hash::Merge::Simple: '0.051'
  Mojolicious: '4.85'
  perl: '5.010001'
resources:
  bugtracker: http://github.com/dotandimet/Mojolicious-Plugin-ConfigHashMerge/issues
  license: http://www.opensource.org/licenses/artistic-license-2.0
  repository: http://github.com/dotandimet/Mojolicious-Plugin-ConfigHashMerge
version: '0.04'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
