---
abstract: unknown
author:
  - 'Marcus Ramberg <mramberg@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.24, CPAN::Meta::Converter version 2.150005'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-RenderSteps
no_index:
  directory:
    - t
    - inc
requires:
  Mojolicious: '6.10'
resources:
  bugtracker: https://github.com/marcusramberg/Mojolicious-Plugin-RenderSteps/issues
  license: http://www.opensource.org/licenses/artistic-license-2.0
  repository: https://github.com/marcusramberg/Mojolicious-Plugin-RenderSteps
version: '0.06'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
