---
abstract: 'A plugin to make authorization a bit easier'
author:
  - 'John Scoles <byterock@hotmail.com>'
build_requires:
  Module::Build: '0.38'
  Mojolicious::Lite: '0'
  Test::Deep: '0.113'
  Test::Exception: '0.32'
  Test::Mojo: '0'
  Test::More: '0'
  strict: '0'
  warnings: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
  Module::Build: '0.38'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.18, CPAN::Meta::Converter version 2.150001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-Authorization
no_index:
  directory:
    - t
    - inc
requires:
  Mojo::Base: '0'
resources:
  bugtracker: https://github.com/byterock/mojolicious-plugin-authorization/issues
  homepage: https://metacpan.org/module/Mojolicious::Plugin::Authorization
  repository: https://github.com/byterock/mojolicious-plugin-authorization
version: '1.05'
