---
abstract: 'Easily create Google JWT for Service Account operations'
author:
  - 'Richard Elberger riche@cpan.org'
build_requires: {}
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.422, CPAN::Meta::Converter version 2.150010'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojo-JWT-Google
provides:
  Mojo::JWT::Google:
    file: lib/Mojo/JWT/Google.pm
    version: '0.06'
requires:
  Mojo::JWT: '0.03'
version: '0.06'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
