---
abstract: 'An XMLRPC message parser/encoder using the Mojo stack'
author:
  - 'Joel Berger, E<lt>joel.a.berger@gmail.comE<gt>'
build_requires: {}
configure_requires:
  Module::Build::Tiny: '0.034'
dynamic_config: 0
generated_by: 'App::ModuleBuildTiny version 0.022, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojo-XMLRPC
provides:
  Mojo::XMLRPC:
    file: lib/Mojo/XMLRPC.pm
    version: '0.05'
  Mojo::XMLRPC::Base64:
    file: lib/Mojo/XMLRPC/Base64.pm
  Mojo::XMLRPC::Message:
    file: lib/Mojo/XMLRPC/Message.pm
  Mojo::XMLRPC::Message::Call:
    file: lib/Mojo/XMLRPC/Message/Call.pm
  Mojo::XMLRPC::Message::Response:
    file: lib/Mojo/XMLRPC/Message/Response.pm
requires:
  Mojolicious: '7.0'
resources:
  bugtracker: http://github.com/jberger/Mojo-XMLRPC/issues
  license: http://dev.perl.org/licenses/
  repository: http://github.com/jberger/Mojo-XMLRPC
version: '0.05'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
