---
abstract: 'Text::Xslate renderer for Mojo'
author:
  - 'gray <gray@cpan.org>'
  - 'hjansen <hjansen@cpan.org>'
build_requires:
  Test::Mojo: '0'
  Test::More: '0.82'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.1001, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MojoX-Renderer-Xslate
no_index:
  directory:
    - t
    - inc
requires:
  Mojolicious: '5.81'
  Text::Xslate: '0.2013'
  Try::Tiny: '0'
  parent: '0'
resources:
  repository: http://github.com/gray/mojox-renderer-xslate
version: '0.13'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
