---
abstract: 'I18N(GNU getext) for Mojolicious.'
author:
  - 'Munenori Sugimura <clicktx@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::More: '0'
configure_requires:
  Module::Build::Tiny: '0.035'
dynamic_config: 0
generated_by: 'Minilla/v3.0.4, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-LocaleTextDomainOO
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Mojolicious::Plugin::LocaleTextDomainOO:
    file: lib/Mojolicious/Plugin/LocaleTextDomainOO.pm
    version: '0.05'
  Mojolicious::Plugin::LocaleTextDomainOO::I18N:
    file: lib/Mojolicious/Plugin/LocaleTextDomainOO.pm
requires:
  I18N::LangTags: '0'
  I18N::LangTags::Detect: '0'
  Locale::TextDomain::OO: '1.033'
  Mojolicious: '7.72'
  perl: '5.010'
resources:
  bugtracker: https://github.com/clicktx/p5-Mojolicious-Plugin-LocaleTextDomainOO/issues
  homepage: https://github.com/clicktx/p5-Mojolicious-Plugin-LocaleTextDomainOO
  repository: git://github.com/clicktx/p5-Mojolicious-Plugin-LocaleTextDomainOO.git
version: '0.05'
