---
abstract: 'Route shortcuts & helpers for REST collections'
author:
  - 'Paul Williams <kwakwa@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.24, CPAN::Meta::Converter version 2.150005'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-Restify
no_index:
  directory:
    - t
    - inc
    - t
requires:
  Mojolicious: '5.27'
  perl: '5.010001'
resources:
  bugtracker: https://github.com/kwakwaversal/mojolicious-plugin-restify/issues
  license: http://www.opensource.org/licenses/artistic-license-2.0
  repository: https://github.com/kwakwaversal/mojolicious-plugin-restify.git
version: '0.08'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
