---
abstract: "Get client's IP address from X-Forwarded-For"
author:
  - 'ziguzagu <ziguzagu@cpan.org>'
build_requires:
  Test::More: '0.98'
configure_requires:
  Module::Build::Tiny: '0.035'
dynamic_config: 0
generated_by: 'Minilla/v2.4.1, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-ClientIP
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Mojolicious::Plugin::ClientIP:
    file: lib/Mojolicious/Plugin/ClientIP.pm
    version: '0.01'
requires:
  Mojolicious: '0'
  perl: '5.010001'
resources:
  bugtracker: https://github.com/sixapart/Mojolicious-Plugin-ClientIP/issues
  homepage: https://github.com/sixapart/Mojolicious-Plugin-ClientIP
  repository: git://github.com/sixapart/Mojolicious-Plugin-ClientIP.git
version: '0.01'
x_authority: cpan:SIXAPART
x_contributors:
  - 'ziguzagu <ziguzagu@gmail.com>'
