---
abstract: 'A quick way of generating a simple Mojolicious app.'
author:
  - 'Kit Peters <popefelix@gmail.com>'
build_requires:
  String::Random: '0'
  Test::Mojo: '0'
  Test::Most: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.039, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Quick
requires:
  Carp: '0'
  Mojo::Base: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/popefelix/Mojolicious-Quick/issues
  homepage: https://github.com/popefelix/Mojolicious-Quick
  repository: https://github.com/popefelix/Mojolicious-Quick.git
version: '0.002'
