---
abstract: 'Export processed assets to directory'
author:
  - 'Heiko Jansen <hjansen@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.009, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-AssetPack-Pipe-ExportToDirectory
requires:
  Mojolicious::Plugin::AssetPack: '1.41'
  PerlIO::gzip: '0.19'
resources:
  repository: https://github.com/heikojansen/mojolicious-plugin-assetpack-pipe-exporttodirectory.git
version: '0.001003'
x_serialization_backend: 'YAML::Tiny version 1.70'
