---
abstract: 'Mojolicious::Plugin::WebAPI - mount WebAPI::DBIC in your Mojolicious app'
author:
  - 'Renee Baecker <reneeb@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.010, CPAN::Meta::Converter version 2.150005'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-WebAPI
requires:
  DBD::SQLite: '0'
  Mojolicious: '7'
  Plack::Util: '0'
  WebAPI::DBIC: '0.004002'
resources:
  bugtracker: http://github.com/reneeb/Mojolicious-Plugin-WebAPI/issues
  homepage: http://github.com/reneeb/Mojolicious-Plugin-WebAPI
  repository: http://github.com/reneeb/Mojolicious-Plugin-WebAPI.git
version: '0.04'
x_serialization_backend: 'YAML::Tiny version 1.69'
