---
abstract: unknown
author:
  - 'Viktor Turskyi <koorchik@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.0401, CPAN::Meta::Converter version 2.150001'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-RenderFile
no_index:
  directory:
    - t
    - inc
requires:
  Mojolicious: '5.78'
  perl: '5.01'
resources:
  repository: https://github.com/koorchik/Mojolicious-Plugin-RenderFile
version: '0.12'
