---
abstract: 'Mojo-based ACME-protocol client'
author:
  - 'Joel Berger, E<lt>joel.a.berger@gmail.comE<gt>'
build_requires:
  Mock::MonkeyPatch: '0'
configure_requires:
  Module::Build::Tiny: '0.034'
dynamic_config: 0
generated_by: 'App::ModuleBuildTiny version 0.022, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojo-ACME
provides:
  Mojo::ACME:
    file: lib/Mojo/ACME.pm
    version: '0.12'
  Mojo::ACME::CA:
    file: lib/Mojo/ACME/CA.pm
  Mojo::ACME::ChallengeServer:
    file: lib/Mojo/ACME/ChallengeServer.pm
  Mojo::ACME::Key:
    file: lib/Mojo/ACME/Key.pm
  Mojolicious::Plugin::ACME:
    file: lib/Mojolicious/Plugin/ACME.pm
  Mojolicious::Plugin::ACME::Command:
    file: lib/Mojolicious/Plugin/ACME/Command.pm
  Mojolicious::Plugin::ACME::Command::acme:
    file: lib/Mojolicious/Plugin/ACME/Command/acme.pm
  Mojolicious::Plugin::ACME::Command::acme::account:
    file: lib/Mojolicious/Plugin/ACME/Command/acme/account.pm
  Mojolicious::Plugin::ACME::Command::acme::account::register:
    file: lib/Mojolicious/Plugin/ACME/Command/acme/account/register.pm
  Mojolicious::Plugin::ACME::Command::acme::cert:
    file: lib/Mojolicious/Plugin/ACME/Command/acme/cert.pm
  Mojolicious::Plugin::ACME::Command::acme::cert::generate:
    file: lib/Mojolicious/Plugin/ACME/Command/acme/cert/generate.pm
requires:
  Crypt::OpenSSL::Bignum: '0'
  Crypt::OpenSSL::PKCS10: '0'
  Crypt::OpenSSL::RSA: '0'
  Digest::SHA: '0'
  MIME::Base64: '3.11'
  Mojolicious: '7.15'
  Safe::Isa: '0'
resources:
  bugtracker: http://github.com/jberger/Mojo-ACME/issues
  license: http://dev.perl.org/licenses/
  repository: http://github.com/jberger/Mojo-ACME
version: '0.12'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
