---
abstract: 'FastCGI Server'
author:
  - 'Árpád Szász <arpad.szasz@plenum.ro>'
build_requires:
  File::Slurp: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.009, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojo-Server-FastCGI
requires:
  Mojolicious: '6.43'
resources:
  bugtracker: https://github.com/arpadszasz/mojo-server-fastcgi/issues
  repository: git://github.com/arpadszasz/mojo-server-fastcgi.git
version: '0.50'
x_serialization_backend: 'YAML::Tiny version 1.70'
