---
abstract: 'no-nonsense CSV handling'
author:
  - 'Zoffix Znet <cpan@zoffix.com>'
build_requires:
  File::Spec: '0'
  File::Temp: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Mojo::Asset::File: '0'
  Mojo::Asset::Memory: '0'
  Mojo::File: '0'
  Test::More: '0'
  Test::Most: '0'
  blib: '1.01'
  constant: '0'
  perl: '5.008'
  strict: '0'
  warnings: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.008'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.008, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojo-CSV
provides:
  Mojo::CSV:
    file: lib/Mojo/CSV.pm
    version: '1.001003'
recommends:
  Text::CSV_XS: '1.20'
requires:
  Carp: '0'
  Mojo::Collection: '0'
  Mojolicious: '7.31'
  Moo: '0'
  MooX::ChainedAttributes: '0'
  Scalar::Util: '0'
  Text::CSV: '0'
  namespace::clean: '0'
  perl: '5.008'
  strictures: '2'
resources:
  bugtracker: https://github.com/zoffixznet/mojo-csv/issues
  homepage: http://metacpan.org/release/Mojo-CSV
  repository: git://github.com/zoffixznet/mojo-csv.git
version: '1.001003'
x_Dist_Zilla:
  perl:
    version: '5.024000'
  plugins:
    -
      class: Dist::Zilla::Plugin::OurPkgVersion
      name: '@Author::ZOFFIX/OurPkgVersion'
      version: '0.10'
    -
      class: Dist::Zilla::Plugin::Pod::Spiffy
      name: '@Author::ZOFFIX/Pod::Spiffy'
      version: '1.001007'
    -
      class: Dist::Zilla::Plugin::PromptIfStale
      config:
        Dist::Zilla::Plugin::PromptIfStale:
          check_all_plugins: 1
          check_all_prereqs: 1
          modules: []
          phase: release
          run_under_travis: 0
          skip:
            - ExtUtils::MakeMaker
            - File::Copy
            - IPC::Open3
            - base
            - strict
            - warnings
      name: '@Author::ZOFFIX/PromptIfStale'
      version: '0.051'
    -
      class: Dist::Zilla::Plugin::GatherDir
      config:
        Dist::Zilla::Plugin::GatherDir:
          exclude_filename: []
          exclude_match: []
          follow_symlinks: 0
          include_dotfiles: 0
          prefix: ''
          prune_directory: []
          root: .
      name: '@Author::ZOFFIX/GatherDir'
      version: '6.008'
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Author::ZOFFIX/PruneCruft'
      version: '6.008'
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Author::ZOFFIX/ManifestSkip'
      version: '6.008'
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Author::ZOFFIX/MetaYAML'
      version: '6.008'
    -
      class: Dist::Zilla::Plugin::License
      name: '@Author::ZOFFIX/License'
      version: '6.008'
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@Author::ZOFFIX/Readme'
      version: '6.008'
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Author::ZOFFIX/ExecDir'
      version: '6.008'
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Author::ZOFFIX/ShareDir'
      version: '6.008'
    -
      class: Dist::Zilla::Plugin::MakeMaker
      config:
        Dist::Zilla::Role::TestRunner:
          default_jobs: 1
      name: '@Author::ZOFFIX/MakeMaker'
      version: '6.008'
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Author::ZOFFIX/Manifest'
      version: '6.008'
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@Author::ZOFFIX/AutoPrereqs'
      version: '6.008'
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Author::ZOFFIX/MetaConfig'
      version: '6.008'
    -
      class: Dist::Zilla::Plugin::Prereqs::AuthorDeps
      name: '@Author::ZOFFIX/Prereqs::AuthorDeps'
      version: '0.006'
    -
      class: Dist::Zilla::Plugin::MinimumPerl
      name: '@Author::ZOFFIX/MinimumPerl'
      version: '1.006'
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      config:
        Dist::Zilla::Plugin::MetaProvides::Package:
          finder_objects:
            -
              class: Dist::Zilla::Plugin::FinderCode
              name: '@Author::ZOFFIX/MetaProvides::Package/AUTOVIV/:InstallModulesPM'
              version: '6.008'
          include_underscores: 0
        Dist::Zilla::Role::MetaProvider::Provider:
          $Dist::Zilla::Role::MetaProvider::Provider::VERSION: '2.002003'
          inherit_missing: '1'
          inherit_version: '1'
          meta_noindex: '1'
        Dist::Zilla::Role::ModuleMetadata:
          Module::Metadata: '1.000031'
          version: '0.004'
      name: '@Author::ZOFFIX/MetaProvides::Package'
      version: '2.004002'
    -
      class: Dist::Zilla::Plugin::InstallGuide
      name: '@Author::ZOFFIX/InstallGuide'
      version: '1.200007'
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      config:
        Dist::Zilla::Role::FileWatcher:
          version: '0.006'
      name: '@Author::ZOFFIX/ReadmeAnyFromPod'
      version: '0.161170'
    -
      class: Dist::Zilla::Plugin::Test::Compile
      config:
        Dist::Zilla::Plugin::Test::Compile:
          bail_out_on_fail: '0'
          fail_on_warning: author
          fake_home: 0
          filename: t/00-compile.t
          module_finder:
            - ':InstallModules'
          needs_display: 0
          phase: test
          script_finder:
            - ':PerlExecFiles'
          skips: []
          switch: []
      name: '@Author::ZOFFIX/Test::Compile'
      version: '2.056'
    -
      class: Dist::Zilla::Plugin::Test::DistManifest
      name: '@Author::ZOFFIX/Test::DistManifest'
      version: '2.000005'
    -
      class: Dist::Zilla::Plugin::Test::EOL
      config:
        Dist::Zilla::Plugin::Test::EOL:
          filename: xt/author/eol.t
          finder:
            - ':ExecFiles'
            - ':InstallModules'
            - ':TestFiles'
          trailing_whitespace: 1
      name: '@Author::ZOFFIX/Test::EOL'
      version: '0.19'
    -
      class: Dist::Zilla::Plugin::Test::Version
      name: '@Author::ZOFFIX/Test::Version'
      version: '1.09'
    -
      class: Dist::Zilla::Plugin::Test::Kwalitee
      config:
        Dist::Zilla::Plugin::Test::Kwalitee:
          filename: xt/release/kwalitee.t
          skiptest: []
      name: '@Author::ZOFFIX/Test::Kwalitee'
      version: '2.12'
    -
      class: Dist::Zilla::Plugin::MetaTests
      name: '@Author::ZOFFIX/MetaTests'
      version: '6.008'
    -
      class: Dist::Zilla::Plugin::Test::CPAN::Meta::JSON
      name: '@Author::ZOFFIX/Test::CPAN::Meta::JSON'
      version: '0.004'
    -
      class: Dist::Zilla::Plugin::MojibakeTests
      name: '@Author::ZOFFIX/MojibakeTests'
      version: '0.8'
    -
      class: Dist::Zilla::Plugin::Test::NoTabs
      config:
        Dist::Zilla::Plugin::Test::NoTabs:
          filename: xt/author/no-tabs.t
          finder:
            - ':InstallModules'
            - ':ExecFiles'
            - ':TestFiles'
      name: '@Author::ZOFFIX/Test::NoTabs'
      version: '0.15'
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@Author::ZOFFIX/PodCoverageTests'
      version: '6.008'
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@Author::ZOFFIX/PodSyntaxTests'
      version: '6.008'
    -
      class: Dist::Zilla::Plugin::Test::Portability
      config:
        Dist::Zilla::Plugin::Test::Portability:
          options: ''
      name: '@Author::ZOFFIX/Test::Portability'
      version: '2.001000'
    -
      class: Dist::Zilla::Plugin::Test::UnusedVars
      name: '@Author::ZOFFIX/Test::UnusedVars'
      version: '2.000007'
    -
      class: Dist::Zilla::Plugin::Test::Pod::LinkCheck
      name: '@Author::ZOFFIX/Test::Pod::LinkCheck'
      version: '1.002'
    -
      class: Dist::Zilla::Plugin::Test::CPAN::Changes
      config:
        Dist::Zilla::Plugin::Test::CPAN::Changes:
          changelog: Changes
      name: '@Author::ZOFFIX/Test::CPAN::Changes'
      version: '0.012'
    -
      class: Dist::Zilla::Plugin::Test::PodSpelling
      config:
        Dist::Zilla::Plugin::Test::PodSpelling:
          directories:
            - bin
            - lib
          spell_cmd: ''
          stopwords: []
          wordlist: Pod::Wordlist
      name: '@Author::ZOFFIX/Test::PodSpelling'
      version: '2.007004'
    -
      class: Dist::Zilla::Plugin::CheckSelfDependency
      config:
        Dist::Zilla::Plugin::CheckSelfDependency:
          finder:
            - ':InstallModules'
        Dist::Zilla::Role::ModuleMetadata:
          Module::Metadata: '1.000031'
          version: '0.004'
      name: '@Author::ZOFFIX/CheckSelfDependency'
      version: '0.011'
    -
      class: Dist::Zilla::Plugin::CheckPrereqsIndexed
      name: '@Author::ZOFFIX/CheckPrereqsIndexed'
      version: '0.020'
    -
      class: Dist::Zilla::Plugin::Test::MinimumVersion
      name: '@Author::ZOFFIX/Test::MinimumVersion'
      version: '2.000007'
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      config:
        Dist::Zilla::Plugin::Git::NextVersion:
          first_version: '1.001001'
          version_by_branch: 0
          version_regexp: (?^:^v(.+)$)
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@Author::ZOFFIX/Git::NextVersion'
      version: '2.039'
    -
      class: Dist::Zilla::Plugin::AutoMetaResources
      name: '@Author::ZOFFIX/AutoMetaResources'
      version: '1.21'
    -
      class: Dist::Zilla::Plugin::CopyFilesFromRelease
      config:
        Dist::Zilla::Plugin::CopyFilesFromRelease:
          filename:
            - README.md
          match: []
      name: '@Author::ZOFFIX/CopyFilesFromRelease'
      version: '0.006'
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Author::ZOFFIX/TestRelease'
      version: '6.008'
    -
      class: Dist::Zilla::Plugin::InstallRelease
      name: '@Author::ZOFFIX/InstallRelease'
      version: '0.008'
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Author::ZOFFIX/ConfirmRelease'
      version: '6.008'
    -
      class: Dist::Zilla::Plugin::Git::Check
      config:
        Dist::Zilla::Plugin::Git::Check:
          untracked_files: die
        Dist::Zilla::Role::Git::DirtyFiles:
          allow_dirty:
            - Changes
            - dist.ini
          allow_dirty_match: []
          changelog: Changes
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@Author::ZOFFIX/Git::Check'
      version: '2.039'
    -
      class: Dist::Zilla::Plugin::Git::Commit
      config:
        Dist::Zilla::Plugin::Git::Commit:
          add_files_in: []
          commit_msg: v%v%n%n%c
        Dist::Zilla::Role::Git::DirtyFiles:
          allow_dirty:
            - Changes
            - dist.ini
          allow_dirty_match: []
          changelog: Changes
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
        Dist::Zilla::Role::Git::StringFormatter:
          time_zone: local
      name: '@Author::ZOFFIX/Git::Commit'
      version: '2.039'
    -
      class: Dist::Zilla::Plugin::Git::Tag
      config:
        Dist::Zilla::Plugin::Git::Tag:
          branch: ~
          changelog: Changes
          signed: 0
          tag: v1.001003
          tag_format: v%v
          tag_message: v%v
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
        Dist::Zilla::Role::Git::StringFormatter:
          time_zone: local
      name: '@Author::ZOFFIX/Git::Tag'
      version: '2.039'
    -
      class: Dist::Zilla::Plugin::Git::Push
      config:
        Dist::Zilla::Plugin::Git::Push:
          push_to:
            - origin
          remotes_must_exist: 1
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@Author::ZOFFIX/Git::Push'
      version: '2.039'
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Author::ZOFFIX/UploadToCPAN'
      version: '6.008'
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: Prereqs
      version: '6.008'
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: recommends
      name: RuntimeRecommends
      version: '6.008'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: '6.008'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: '6.008'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: '6.008'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExtraTestFiles'
      version: '6.008'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: '6.008'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':PerlExecFiles'
      version: '6.008'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: '6.008'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: '6.008'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':AllFiles'
      version: '6.008'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':NoFiles'
      version: '6.008'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: '@Author::ZOFFIX/MetaProvides::Package/AUTOVIV/:InstallModulesPM'
      version: '6.008'
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: '0'
    version: '6.008'
x_serialization_backend: 'YAML::Tiny version 1.69'
