---
abstract: 'Config::Simple::Extended '
author:
  - '& COPYRIGHT'
build_requires:
  Module::Build::Tiny: '0.039'
  Test::Pod: '1.48'
configure_requires:
  Module::Build::Tiny: '0.036'
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.4, Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-ConfigSimple
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Config::Simple::Extended: '0.15'
  Mojolicious: '0.00'
  Test::Exception: '0.32'
resources:
  bugtracker: https://github.com/hesco/Mojolicious-Plugin-ConfigSimple/issues
  homepage: https://github.com/hesco/Mojolicious-Plugin-ConfigSimple
  repository: https://github.com/hesco/Mojolicious-Plugin-ConfigSimple.git
version: '0.06'
x_contributors:
  - 'Renee <reb@perl-services.de>'
  - 'hesco <hesco@campaignfoundations.com>'
