---
abstract: 'run test scripts via browser'
author:
  - 'Renee Baecker <reneeb@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.029, CPAN::Meta::Converter version 2.142060'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-Prove
requires:
  App::Prove: '0'
  Capture::Tiny: '0'
  Cwd: '0'
  File::Basename: '0'
  File::Find::Rule: '0'
  File::Spec: '0'
  Mojolicious: '4.50'
  Mojolicious::Plugin::PPI: '0'
  Test::LongString: '0'
resources:
  bugtracker: http://github.com/reneeb/Mojolicious-Plugin-Prove/issues
  homepage: http://github.com/reneeb/Mojolicious-Plugin-Prove
  repository: http://github.com/reneeb/Mojolicious-Plugin-Prove.git
version: '0.08'
