---
author:
  - 'Nicolas Mendoza <mendoza@pvv.ntnu.no>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  IO::Compress::Gzip: 0
  Test::More: 0
  Time::HiRes: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
  Module::Install: 0
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.16'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojo-UserAgent-Cached
no_index:
  directory:
    - inc
    - t
requires:
  Algorithm::LCSS: 0
  CHI: 0
  Data::Serializer: 0
  Devel::StackTrace: 0
  English: 0
  File::Basename: 0
  File::Path: 0
  File::Spec: 0
  List::Util: '1.29'
  Mojolicious: '7.15'
  POSIX: 0
  Readonly: 0
  String::Truncate: 0
  Time::HiRes: 0
  perl: 5.10.1
resources:
  license: http://dev.perl.org/licenses/
version: '1.06'
