---
abstract: 'Turn a (tcp) stream into a NetstringStream'
author:
  - 'Wieger Opmeer <wiegerop@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.009, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MojoX-NetstringStream
requires:
  Mojolicious: '6.00'
  perl: '5.010'
resources:
  bugtracker: https://github.com/a6502/MojoX-NetstringStream/issues
  homepage: https://github.com/a6502/MojoX-NetstringStream
  repository: https://github.com/a6502/MojoX-NetstringStream.git
version: '0.06'
x_serialization_backend: 'YAML::Tiny version 1.70'
