---
abstract: 'Client IP header handling for Mojolicious requests'
author:
  - 'binary.com <BINARY@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::CheckDeps: '0.010'
  Test::Mojo: '0'
  Test::More: '0.94'
  Test::Warnings: '0'
  perl: '5.014000'
configure_requires:
  ExtUtils::MakeMaker: '6.64'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.010, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-ClientIP-Pluggable
requires:
  Data::Validate::IP: '0.25'
  Mojolicious: '0'
  perl: '5.014000'
resources:
  bugtracker: https://github.com/binary-com/perl-Mojolicious-Plugin-ClientIP-CloudFlare/issues
  repository: git://github.com/binary-com/perl-Mojolicious-Plugin-ClientIP-CloudFlare.git
version: '0.01'
x_serialization_backend: 'YAML::Tiny version 1.69'
