---
abstract: 'Mojo::Log with More details'
author:
  - 'Olivier Duclos <odc@cpan.org>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojo-Log-More
no_index:
  directory:
    - t
    - inc
    - t
requires:
  File::Spec: '0'
  Mojolicious: '5.0'
  Time::Piece: '0'
  perl: '5.010'
resources:
  bugtracker: http://github.com/oliwer/mojo-log-more/issues
  license: http://www.opensource.org/licenses/artistic-license-2.0
  repository: http://github.com/oliwer/mojo-log-more
version: '1.02'
