---
abstract: 'Mojolicious and Async MySQL'
author:
  - 'Jan Henning Thorsen <jhthorsen@cpan.org>'
build_requires:
  Test::More: '0.90'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.24, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojo-mysql
no_index:
  directory:
    - t
    - inc
requires:
  DBD::mysql: '4.042'
  Mojolicious: '7.55'
  SQL::Abstract: '1.81'
resources:
  bugtracker: https://github.com/jhthorsen/mojo-mysql/issues
  homepage: https://github.com/jhthorsen/mojo-mysql
  repository: https://github.com/jhthorsen/mojo-mysql.git
version: '1.06'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
