---
abstract: 'JSON-RPC 2.0 over HTTP'
author:
  - 'Alex Efros <powerman@cpan.org>'
build_requires:
  JSON::RPC2::Client: '0'
  Mojolicious::Lite: '0'
  Test::Exception: '0'
  Test::Mojo: '0'
  Test::More: '0'
configure_requires:
  Module::Build::Tiny: '0.034'
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.18, Dist::Zilla version 6.011, CPAN::Meta::Converter version 2.150010'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-JSONRPC2
no_index:
  directory:
    - eg
    - examples
    - inc
    - share
    - t
    - xt
provides:
  Mojolicious::Plugin::JSONRPC2:
    file: lib/Mojolicious/Plugin/JSONRPC2.pm
    version: v2.0.1
requires:
  JSON::RPC2: v0.4.0
  JSON::RPC2::Server: v0.4.0
  JSON::XS: '0'
  Mojo::Base: '0'
  Mojolicious: '5.11'
  perl: '5.010001'
resources:
  bugtracker: https://github.com/powerman/perl-Mojolicious-Plugin-JSONRPC2/issues
  homepage: https://github.com/powerman/perl-Mojolicious-Plugin-JSONRPC2
  repository: https://github.com/powerman/perl-Mojolicious-Plugin-JSONRPC2.git
version: v2.0.1
x_serialization_backend: 'YAML::Tiny version 1.73'
