---
abstract: 'Simple role-based authorization'
author:
  - 'Paul Williams <kwakwa@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.142060'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-SimpleAuthorization
no_index:
  directory:
    - t
    - inc
    - t
requires:
  Mojolicious: '4.72'
  perl: '5.010001'
resources:
  bugtracker: https://github.com/kwakwaversal/mojolicious-plugin-simpleauthorization/issues
  license: http://www.opensource.org/licenses/artistic-license-2.0
  repository: https://github.com/kwakwaversal/mojolicious-plugin-simpleauthorization.git
version: '0.02'
