---
abstract: 'A plugin for dispatching and handling sync/async events'
author:
  - 'Adrian Crisan <adrian.crisan88@gmail.com>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
  Mojo::Base: '0'
  Mojolicious::Plugin: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.1, CPAN::Meta::Converter version 2.133380'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-Events
no_index:
  directory:
    - t
    - inc
requires:
  perl: '5.006'
version: '0.02'
