---
abstract: 'Browses online documentation of your Mojolicious application'
author:
  - 'Viliam Pucik <viliam.pucik@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.24, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-DOCRenderer
no_index:
  directory:
    - t
    - inc
    - t
requires:
  Mojolicious: '7.43'
  perl: '5.010001'
resources:
  bugtracker: https://github.com/viliampucik/Mojolicious-Plugin-DocRenderer/issues
  homepage: https://github.com/viliampucik/Mojolicious-Plugin-DocRenderer
  license: http://www.opensource.org/licenses/artistic-license-2.0
  repository: https://github.com/viliampucik/Mojolicious-Plugin-DocRenderer.git
version: '5.01'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
