---
abstract: unknown
author:
  - 'Binary.com <perl@binary.com>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.02, CPAN::Meta::Converter version 2.143240'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-RedisSubscriber
no_index:
  directory:
    - t
    - inc
requires:
  Cache::RedisDB: '0'
  Mojo::EventEmitter: '0'
  Mojo::Redis: '0'
  Mojolicious: '0'
  Try::Tiny: '0'
  YAML::XS: '0'
  perl: '5.006'
version: v0.0.1
