---
abstract: 'Complete control over CORS'
author:
  - 'Alex Efros <powerman@cpan.org>'
build_requires:
  Mojolicious::Lite: '0'
  Test::Mojo: '0'
  Test::More: '0'
configure_requires:
  Module::Build::Tiny: '0.034'
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.18, Dist::Zilla version 6.011, CPAN::Meta::Converter version 2.150010'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-SecureCORS
no_index:
  directory:
    - eg
    - examples
    - inc
    - share
    - t
    - xt
provides:
  Mojolicious::Plugin::SecureCORS:
    file: lib/Mojolicious/Plugin/SecureCORS.pm
    version: v2.0.1
requires:
  List::MoreUtils: '0.34'
  Mojo::Base: '0'
  Mojolicious: '6'
  perl: '5.010001'
resources:
  bugtracker: https://github.com/powerman/perl-Mojolicious-Plugin-SecureCORS/issues
  homepage: https://github.com/powerman/perl-Mojolicious-Plugin-SecureCORS
  repository: https://github.com/powerman/perl-Mojolicious-Plugin-SecureCORS.git
version: v2.0.1
x_serialization_backend: 'YAML::Tiny version 1.73'
