---
abstract: 'Provides back compat functionality for 0.x series of AssetPack'
author:
  - 'Jan Henning Thorsen <jhthorsen@cpan.org>'
build_requires:
  Test::More: '0.88'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.24, CPAN::Meta::Converter version 2.150005'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-AssetPack-Backcompat
no_index:
  directory:
    - t
    - inc
requires:
  CSS::Minifier::XS: '0.09'
  JavaScript::Minifier::XS: '0.11'
  Mojolicious::Plugin::AssetPack: '0.20'
resources:
  bugtracker: https://github.com/jhthorsen/mojolicious-plugin-assetpack-backcompat/issues
  homepage: https://github.com/jhthorsen/mojolicious-plugin-assetpack-backcompat
  repository: https://github.com/jhthorsen/mojolicious-plugin-assetpack-backcompat.git
version: '1.24'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
