---
abstract: 'Simple Twitter Client'
author:
  - 'Fayland Lam <fayland@gmail.com>'
build_requires:
  Test::More: '0.96'
configure_requires:
  Module::Build::Tiny: '0.034'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.005, Dist::Milla version v1.0.16, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MojoX-Twitter
no_index:
  directory:
    - eg
    - examples
    - inc
    - share
    - t
    - xt
requires:
  Digest::SHA: '0'
  Mojolicious: '0'
  URI::Escape: '0'
resources:
  bugtracker: https://github.com/fayland/perl-MojoX-Twitter/issues
  homepage: https://github.com/fayland/perl-MojoX-Twitter
  repository: https://github.com/fayland/perl-MojoX-Twitter.git
version: '0.06'
