---
abstract: 'A simple perl wrapper of Zabbix API.'
author:
  - 'Orange <bollwarm@ijz.me>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.16, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojo-Zabbix
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
  Mojolicious: '6.11'
  POSIX: '0'
  Scalar::Util: '0'
  Time::HiRes: '0'
resources:
  repository: https://github.com/bollwarm/Mojo-Zabbix
version: '0.11'
