---
abstract: 'Pure-Perl non-blocking I/O Redis driver'
author:
  - 'Jan Henning Thorsen <jhthorsen@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Sort::Versions: '1.5'
  Test::More: '0.88'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.3, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojo-Redis2
no_index:
  directory:
    - t
    - inc
requires:
  Mojolicious: '7.50'
  Protocol::Redis: '1.0'
resources:
  bugtracker: https://github.com/jhthorsen/mojo-redis2/issues
  homepage: https://github.com/jhthorsen/mojo-redis2
  repository: https://github.com/jhthorsen/mojo-redis2.git
version: '0.31'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
