---
abstract: 'use Googles "No CAPTCHA reCAPCTHA" (reCAPTCHA v2) service in Mojolicious apps'
author:
  - 'Heiko Jansen <hjansen@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.041, CPAN::Meta::Converter version 2.143240'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-ReCAPTCHAv2
requires:
  IO::Socket::SSL: '1.75'
  Mojolicious: '0'
resources:
  repository: https://github.com/heikojansen/mojolicious-plugin-recaptchav2.git
version: '0.4'
