---
abstract: 'add throttling support to Mojo::UserAgent'
author:
  - 'Alex Efros <powerman@cpan.org>'
build_requires:
  Sub::Throttler::Limit: '0'
  Test::More: '0'
  ojo: '0'
configure_requires:
  Module::Build::Tiny: '0.034'
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.18, Dist::Zilla version 6.011, CPAN::Meta::Converter version 2.150010'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MojoX-UserAgent-Throttler
no_index:
  directory:
    - eg
    - examples
    - inc
    - share
    - t
    - xt
provides:
  MojoX::UserAgent::Throttler:
    file: lib/MojoX/UserAgent/Throttler.pm
    version: v1.0.3
requires:
  Mojo::Base: '0'
  Mojo::UserAgent: '0'
  Mojo::Util: '0'
  Mojolicious: '7.13'
  Sub::Throttler: v0.2.0
  Sub::Util: '1.40'
  perl: '5.010001'
resources:
  bugtracker: https://github.com/powerman/perl-MojoX-UserAgent-Throttler/issues
  homepage: https://github.com/powerman/perl-MojoX-UserAgent-Throttler
  repository: https://github.com/powerman/perl-MojoX-UserAgent-Throttler.git
version: v1.0.3
x_serialization_backend: 'YAML::Tiny version 1.73'
