---
abstract: 'postgres advisory locks for Mojolicious application'
author:
  - 'Copyright (C) Alexander Onokhov <onokhov@cpan.org>.'
build_requires:
  Digest::Crc32: '0'
  Test::More: '0.98'
configure_requires:
  Module::Build::Tiny: '0.035'
dynamic_config: 0
generated_by: 'Minilla/v3.0.14, CPAN::Meta::Converter version 2.142060'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-PgLock
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Mojolicious::Plugin::PgLock:
    file: lib/Mojolicious/Plugin/PgLock.pm
    version: '0.01'
  Mojolicious::Plugin::PgLock::Sentinel:
    file: lib/Mojolicious/Plugin/PgLock/Sentinel.pm
requires:
  perl: '5.008001'
resources:
  bugtracker: https://github.com/onokhov/Mojolicious-Plugin-PgLock/issues
  homepage: https://github.com/onokhov/Mojolicious-Plugin-PgLock
  repository: git://github.com/onokhov/Mojolicious-Plugin-PgLock.git
version: '0.01'
x_contributors:
  - 'ccn <ccnweb@gmail.com>'
