---
abstract: 'Allow Mojo::UserAgent to execute digest auth requests'
author:
  - 'Jan Henning Thorsen <jhthorsen@cpan.org>'
build_requires:
  Test::More: '0.88'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.0401, CPAN::Meta::Converter version 2.150001'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojo-UserAgent-DigestAuth
no_index:
  directory:
    - t
    - inc
requires:
  Mojolicious: '5.00'
resources:
  bugtracker: https://github.com/jhthorsen/mojo-useragent-digestauth/issues
  homepage: https://github.com/jhthorsen/mojo-useragent-digestauth
  repository: https://github.com/jhthorsen/mojo-useragent-digestauth.git
version: '0.04'
