---
abstract: 'WebSocket proxy for JSON-RPC 2.0 server'
author:
  - 'binary.com <BINARY@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::CheckDeps: '0.010'
  Test::MockModule: '0'
  Test::MockObject: '0'
  Test::Mojo: '0'
  Test::More: '0.94'
  Test::Simple: '0.44'
  Test::TCP: '0'
  perl: '5.014000'
configure_requires:
  ExtUtils::MakeMaker: '6.64'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.007, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojo-WebSocketProxy
requires:
  Class::Method::Modifiers: '0'
  Data::UUID: '0'
  Future: '0'
  Guard: '0'
  JSON: '0'
  JSON::XS: '0'
  MojoX::JSON::RPC: '0'
  Mojolicious: '0'
  Scalar::Util: '0'
  Variable::Disposition: '0'
  perl: '5.014000'
resources:
  bugtracker: https://github.com/binary-com/perl-Mojo-WebSocketProxy/issues
  repository: git://github.com/binary-com/perl-Mojo-WebSocketProxy.git
version: '0.06'
x_serialization_backend: 'YAML::Tiny version 1.66'
