---
abstract: 'Mason 1 (aka HTML::Mason 1.x) Renderer Plugin.'
author:
  - 'Alexandre SIMON <asimon@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-Mason1Renderer
no_index:
  directory:
    - t
    - inc
requires:
  HTML::Mason: 1.3
  Mojolicious: 1.11
  Test::More: 0
version: 0.03
