---
abstract: Mojolicious::Plugin::SemanticUIPageNavigator
author:
  - 'yanxq <yanxueqing621@163.com>'
build_requires:
  Module::Build: 0.28
  Module::Find: 0
  Mojolicious::Lite: 0
  Test::Mojo: 0
  Test::More: 0
  Test::Pod: 0
  strict: 0
  warnings: 0
configure_requires:
  Module::Build: 0.28
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.031, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-SemanticUIPageNavigator
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Modern::Perl: 0
  Mojo::Base: 0
  Mojo::ByteStream: 0
  Mojo::DOM: 0
  POSIX: 0
version: 0.0.3
