---
abstract: 'non-blocking SlackRTM client using Mojo::IOLoop'
author:
  - 'Shoichi Kaji <skaji@cpan.org>'
build_requires:
  Test::More: '0.98'
configure_requires:
  Module::Build::Tiny: '0.034'
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.18, Dist::Zilla version 6.009, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojo-SlackRTM
no_index:
  directory:
    - eg
    - examples
    - inc
    - share
    - t
    - xt
requires:
  IO::Socket::SSL: '0'
  Mojolicious: '6.00'
  perl: '5.010001'
resources:
  bugtracker: https://github.com/skaji/Mojo-SlackRTM/issues
  homepage: https://github.com/skaji/Mojo-SlackRTM
  repository: https://github.com/skaji/Mojo-SlackRTM.git
version: '0.04'
x_contributors:
  - 'Doug Bell <doug@preaction.me>'
  - 'Joel Berger <joel.a.berger@gmail.com>'
  - 'Shoichi Kaji <skaji@outlook.com>'
x_serialization_backend: 'YAML::Tiny version 1.70'
x_static_install: 1
