---
abstract: 'Plift ♥ Mojolicious'
author:
  - 'Carlos Fernando Avila Gratz <cafe@kreato.com.br>'
build_requires:
  Test::Mojo: '0'
  Test::More: '0.98'
configure_requires:
  Module::Build::Tiny: '0.035'
dynamic_config: 0
generated_by: 'Minilla/v3.0.3, CPAN::Meta::Converter version 2.150001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-Plift
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Mojolicious::Plugin::Plift:
    file: lib/Mojolicious/Plugin/Plift.pm
    version: '0.02'
requires:
  Plift: '0.09'
  XML::LibXML::jQuery: '0'
  perl: '5.008001'
resources:
  bugtracker: https://github.com/cafe01/Mojolicious-Plugin-Plift/issues
  homepage: https://github.com/cafe01/Mojolicious-Plugin-Plift
  repository: git://github.com/cafe01/Mojolicious-Plugin-Plift.git
version: '0.02'
x_authority: cpan:CAFEGRATZ
