---
abstract: 'Mojolicious Plugin'
author:
  - 'Brian Medley <bpmedley@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.043, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-ForkCart
requires:
  Mojolicious::Plugin::ForkCall: '0'
version: '0.03'
