---
abstract: 'Tools for structured benchmarking and profiling'
author:
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  Test::More: '0'
  perl: '5.008001'
configure_requires:
  ExtUtils::MakeMaker: '6.17'
  perl: '5.008001'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.043, CPAN::Meta::Converter version 2.150001'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Benchmark-Lab
no_index:
  directory:
    - corpus
    - examples
    - t
    - xt
  package:
    - DB
provides:
  Benchmark::Lab:
    file: lib/Benchmark/Lab.pm
    version: '0.001'
requires:
  Carp: '0'
  Devel::NYTProf: '0'
  List::Util: '0'
  Time::HiRes: '0'
  perl: '5.008001'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/dagolden/Benchmark-Lab/issues
  homepage: https://github.com/dagolden/Benchmark-Lab
  repository: https://github.com/dagolden/Benchmark-Lab.git
version: '0.001'
x_authority: cpan:DAGOLDEN
