---
abstract: 'Mojolicious Plugin'
author:
  - 'Vidar Tyldum <vidar@tyldum.com>'
build_requires: {}
configure_requires:
  Module::Build::Tiny: '0.035'
dynamic_config: 0
generated_by: 'Minilla/v3.0.17, CPAN::Meta::Converter version 2.150001'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-NamedHelpers
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Mojolicious::Plugin::NamedHelpers:
    file: lib/Mojolicious/Plugin/NamedHelpers.pm
    version: '0.03'
requires:
  Mojolicious: '0'
  Sub::Util: '0'
resources:
  bugtracker: https://github.com/tyldum/Mojolicious-Plugin-NamedHelpers/issues
  homepage: https://github.com/tyldum/Mojolicious-Plugin-NamedHelpers
  repository: git://github.com/tyldum/Mojolicious-Plugin-NamedHelpers.git
version: '0.03'
x_authority: cpan:TYLDUM
x_contributors:
  - 'Dan Book <grinnz@grinnz.com>'
