---
abstract: 'process .elm files'
author:
  - 'Sandeep Chayapathi <sandeep@themighty.com>'
build_requires:
  Test::More: '0.88'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.24, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-AssetPack-Pipe-ElmLang
no_index:
  directory:
    - t
    - inc
requires:
  perl: v5.10.0
resources:
  bugtracker: https://github.com/csandeep/mojolicious-plugin-assetpack-pipe-elmlang/issues
  homepage: https://github.com/csandeep/mojolicious-plugin-assetpack-pipe-elmlang
  repository: https://github.com/csandeep/mojolicious-plugin-assetpack-pipe-elmlang.git
version: '0.4'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
