---
abstract: 'Execute external programs or internal code blocks as separate process.'
author:
  - 'Ettore Di Giacinto <edigiacinto@suse.com>'
build_requires:
  Test::More: '0.98'
configure_requires:
  Module::Build: '0.4005'
  perl: 5.008_001
dynamic_config: 0
generated_by: 'Minilla/v3.0.13, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojo-IOLoop-ReadWriteProcess
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Mojo::IOLoop::ReadWriteProcess:
    file: lib/Mojo/IOLoop/ReadWriteProcess.pm
    version: '0.20'
  Mojo::IOLoop::ReadWriteProcess::CGroup:
    file: lib/Mojo/IOLoop/ReadWriteProcess/CGroup.pm
  Mojo::IOLoop::ReadWriteProcess::CGroup::v1:
    file: lib/Mojo/IOLoop/ReadWriteProcess/CGroup/v1.pm
  Mojo::IOLoop::ReadWriteProcess::CGroup::v1::Cpuacct:
    file: lib/Mojo/IOLoop/ReadWriteProcess/CGroup/v1/Cpuacct.pm
  Mojo::IOLoop::ReadWriteProcess::CGroup::v1::Cpuset:
    file: lib/Mojo/IOLoop/ReadWriteProcess/CGroup/v1/Cpuset.pm
  Mojo::IOLoop::ReadWriteProcess::CGroup::v1::Devices:
    file: lib/Mojo/IOLoop/ReadWriteProcess/CGroup/v1/Devices.pm
  Mojo::IOLoop::ReadWriteProcess::CGroup::v1::Freezer:
    file: lib/Mojo/IOLoop/ReadWriteProcess/CGroup/v1/Freezer.pm
  Mojo::IOLoop::ReadWriteProcess::CGroup::v1::Memory:
    file: lib/Mojo/IOLoop/ReadWriteProcess/CGroup/v1/Memory.pm
  Mojo::IOLoop::ReadWriteProcess::CGroup::v1::Netcls:
    file: lib/Mojo/IOLoop/ReadWriteProcess/CGroup/v1/Netcls.pm
  Mojo::IOLoop::ReadWriteProcess::CGroup::v1::Netprio:
    file: lib/Mojo/IOLoop/ReadWriteProcess/CGroup/v1/Netprio.pm
  Mojo::IOLoop::ReadWriteProcess::CGroup::v1::PID:
    file: lib/Mojo/IOLoop/ReadWriteProcess/CGroup/v1/PID.pm
  Mojo::IOLoop::ReadWriteProcess::CGroup::v1::RDMA:
    file: lib/Mojo/IOLoop/ReadWriteProcess/CGroup/v1/RDMA.pm
  Mojo::IOLoop::ReadWriteProcess::CGroup::v2:
    file: lib/Mojo/IOLoop/ReadWriteProcess/CGroup/v2.pm
  Mojo::IOLoop::ReadWriteProcess::CGroup::v2::CPU:
    file: lib/Mojo/IOLoop/ReadWriteProcess/CGroup/v2/CPU.pm
  Mojo::IOLoop::ReadWriteProcess::CGroup::v2::IO:
    file: lib/Mojo/IOLoop/ReadWriteProcess/CGroup/v2/IO.pm
  Mojo::IOLoop::ReadWriteProcess::CGroup::v2::Memory:
    file: lib/Mojo/IOLoop/ReadWriteProcess/CGroup/v2/Memory.pm
  Mojo::IOLoop::ReadWriteProcess::CGroup::v2::PID:
    file: lib/Mojo/IOLoop/ReadWriteProcess/CGroup/v2/PID.pm
  Mojo::IOLoop::ReadWriteProcess::CGroup::v2::RDMA:
    file: lib/Mojo/IOLoop/ReadWriteProcess/CGroup/v2/RDMA.pm
  Mojo::IOLoop::ReadWriteProcess::Container:
    file: lib/Mojo/IOLoop/ReadWriteProcess/Container.pm
  Mojo::IOLoop::ReadWriteProcess::Exception:
    file: lib/Mojo/IOLoop/ReadWriteProcess/Exception.pm
  Mojo::IOLoop::ReadWriteProcess::Namespace:
    file: lib/Mojo/IOLoop/ReadWriteProcess/Namespace.pm
  Mojo::IOLoop::ReadWriteProcess::Pool:
    file: lib/Mojo/IOLoop/ReadWriteProcess/Pool.pm
  Mojo::IOLoop::ReadWriteProcess::Queue:
    file: lib/Mojo/IOLoop/ReadWriteProcess/Queue.pm
  Mojo::IOLoop::ReadWriteProcess::Session:
    file: lib/Mojo/IOLoop/ReadWriteProcess/Session.pm
requires:
  Mojolicious: '7.24'
resources:
  bugtracker: https://github.com/mudler/Mojo-IOLoop-ReadWriteProcess/issues
  homepage: https://github.com/mudler/Mojo-IOLoop-ReadWriteProcess
  repository: git://github.com/mudler/Mojo-IOLoop-ReadWriteProcess.git
version: '0.20'
x_contributors:
  - 'Ettore Di Giacinto <mudler@gentoo.org>'
  - 'Ettore Di Giacinto <mudler@users.noreply.github.com>'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
