---
abstract: 'Narada configuration plugin'
author:
  - 'Alex Efros <powerman@cpan.org>'
build_requires:
  Test::More: '0'
configure_requires:
  Module::Build::Tiny: '0.034'
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.18, Dist::Zilla version 6.011, CPAN::Meta::Converter version 2.150010'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-Narada
no_index:
  directory:
    - eg
    - examples
    - inc
    - share
    - t
    - xt
provides:
  Mojolicious::Plugin::Narada:
    file: lib/Mojolicious/Plugin/Narada.pm
    version: v1.0.1
requires:
  Mojo::Base: '0'
  MojoX::Log::Fast: '0'
  Mojolicious: '6'
  Narada: '0'
  Narada::Config: '0'
  Narada::Lock: '0'
  Scalar::Util: '0'
  perl: '5.010001'
resources:
  bugtracker: https://github.com/powerman/perl-Mojolicious-Plugin-Narada/issues
  homepage: https://github.com/powerman/perl-Mojolicious-Plugin-Narada
  repository: https://github.com/powerman/perl-Mojolicious-Plugin-Narada.git
version: v1.0.1
x_serialization_backend: 'YAML::Tiny version 1.73'
