---
abstract: 'Mongol plugin for Mojolicious'
author:
  - 'Tudor Marghidanu'
build_requires: {}
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.422, CPAN::Meta::Converter version 2.150001'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-Mongol
provides:
  Mojolicious::Plugin::Mongol:
    file: lib/Mojolicious/Plugin/Mongol.pm
    version: '1.0'
requires:
  Mojolicious: '0'
  Mongol: '0'
  Moose: '0'
  Test::More: '0'
  Test::Pod: '0'
  Test::Pod::Coverage: '0'
version: '1.0'
