---
abstract: "show server status like Apache's mod_status"
author:
  - 'fu kai <iakuf@163.com>'
build_requires:
  Test::More: '0.9'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.68, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-ServerStatus
no_index:
  directory:
    - t
    - inc
requires:
  Fcntl: '0'
  IO::Handle: '0'
  JSON: '2.53'
  Mojolicious: '4.90'
  Net::CIDR::Lite: '0'
  Parallel::Scoreboard: '0.03'
  perl: '5.010001'
resources:
  bugtracker: https://github.com/iakuf/mojolicious-plugin-serverstatus/issues
  license: http://dev.perl.org/licenses/
  repository: https://github.com/iakuf/mojolicious-plugin-serverstatus
version: '0.04'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
