before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq phantomjs
install:
  - cpanm --quiet --installdeps --with-develop --notest .
  - mbtiny regenerate
  - cpanm --quiet --installdeps --notest .
language: perl
perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
