---
abstract: 'IRC Client for the Mojo IOLoop'
author:
  - 'Jan Henning Thorsen <jhthorsen@cpan.org>'
build_requires:
  Test::More: '0.88'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.24, CPAN::Meta::Converter version 2.150005'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojo-IRC
no_index:
  directory:
    - t
    - inc
requires:
  IRC::Utils: '0.12'
  List::Util: '1.33'
  Mojolicious: '7.18'
  Parse::IRC: '1.20'
  Unicode::UTF8: '0.59'
resources:
  bugtracker: https://github.com/jhthorsen/mojo-irc/issues
  homepage: https://github.com/jhthorsen/mojo-irc
  repository: https://github.com/jhthorsen/mojo-irc.git
version: '0.44'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
