---
abstract: 'Create a graph from a MojoX::Routes object'
author:
  - 'Pedro Melo <melo@cpan.org>'
build_requires:
  Pod::Coverage::TrustPod: '0'
  Test::CPAN::Meta: '0'
  Test::More: '0.96'
  Test::Pod: '0'
  Test::Pod::Coverage: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.008, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MojoX-Routes-AsGraph
requires:
  Graph::Easy: '0'
  Mojolicious: '0'
  perl: '5.008'
resources:
  repository: http://github.com/melo/mojox-routes-asgraph/
version: '0.07'
x_serialization_backend: 'YAML::Tiny version 1.69'
