---
abstract: unknown
author:
  - 'Kostya Ten <kostya@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.1001, CPAN::Meta::Converter version 2.150005'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-RussianPost
no_index:
  directory:
    - t
    - inc
requires:
  Mojolicious: '7.06'
version: '0.01'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
