---
abstract: 'Use the current Log::Any adapter from Mojolicious'
author:
  - 'José Joaquín Atria <jjatria@cpan.org>'
build_requires:
  FindBin: '0'
  Log::Any::Adapter: '0'
  Mojolicious::Lite: '0'
  Test::Mojo: '0'
  Test::More: '1.302067'
  Test::Pod: '1.51'
  perl: v5.10.0
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.009, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MojoX-Log-Any
provides:
  MojoX::Log::Any:
    file: lib/MojoX/Log/Any.pm
    version: '0.005'
requires:
  Class::Load: '0.23'
  Class::Method::Modifiers: '2.12'
  Log::Any: '0'
  Log::Any::Adapter::MojoLog: '0.02'
  Log::Any::Plugin: '0'
  Log::Any::Plugin::Format: '0.02'
  Log::Any::Plugin::History: '0.01'
  perl: v5.10.0
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://gitlab.com/jjatria/MojoX-Log-Any/issues
  repository: https://gitlab.com/jjatria/MojoX-Log-Any
version: '0.005'
x_serialization_backend: 'YAML::Tiny version 1.70'
