---
abstract: 'use the JavaScript console from Mojolicious applications'
author:
  - 'Renee Baecker <reneeb@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.032, CPAN::Meta::Converter version 2.143240'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-JavaScript-Console
requires:
  JavaScript::Console: 0
  Mojolicious: 3.51
  Test::CheckManifest: 1.24
  Test::More: 0
resources:
  bugtracker: http://github.com/reneeb/Mojolicious-Plugin-JavaScript-Console/issues
  homepage: http://github.com/reneeb/Mojolicious-Plugin-JavaScript-Console
  repository: http://github.com/reneeb/Mojolicious-Plugin-JavaScript-Console.git
version: 0.02
