---
abstract: 'Have a Hash make some Mojo routes'
author:
  - 'John Scoles <byterock@hotmail.com>'
build_requires:
  Lingua::EN::Inflect: '1'
  Module::Build: '0.38'
  Test::Mojo: '0'
  Test::More: '0'
  strict: '0'
  warnings: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
  Module::Build: '0.38'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.18, CPAN::Meta::Converter version 2.150001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-Routes-Restful
no_index:
  directory:
    - t
    - inc
requires:
  Mojo::Base: '0'
resources:
  bugtracker: https://github.com/byterock/mojolicious-plugin-routes-restful/issues
  homepage: https://metacpan.org/module/Mojolicious::Plugin::Routes::Restful
  repository: https://github.com/byterock/mojolicious-plugin-routes-restful
version: '0.03'
