---
abstract: 'Mojolicious Plugin'
author:
  - 'Renee Baecker <reneeb@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.010, CPAN::Meta::Converter version 2.150005'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-FormFieldsFromJSON-Date
provides:
  Mojolicious::Plugin::FormFieldsFromJSON::Date:
    file: lib/Mojolicious/Plugin/FormFieldsFromJSON/Date.pm
    version: '1.00'
requires:
  Mojolicious: '5.73'
  Mojolicious::Plugin::FormFieldsFromJSON: '1.00'
  Time::Piece: '0'
  perl: '5.010'
resources:
  bugtracker: http://github.com/reneeb/Mojolicious-Plugin-FormFieldsFromJSON-Date/issues
  homepage: http://github.com/reneeb/Mojolicious-Plugin-FormFieldsFromJSON-Date
  repository: http://github.com/reneeb/Mojolicious-Plugin-FormFieldsFromJSON-Date.git
version: '1.00'
x_serialization_backend: 'YAML::Tiny version 1.69'
