---
abstract: 'HTML::Template::Compiled renderer for Mojo'
author:
  - 'Renee Baecker <reneeb@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.029, CPAN::Meta::Converter version 2.142060'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MojoX-Renderer-HTC
requires:
  HTML::Template::Compiled: '0.99'
  Mojolicious: '3.51'
resources:
  bugtracker: http://github.com/reneeb/MojoX-Renderer-HTC/issues
  homepage: http://github.com/reneeb/MojoX-Renderer-HTC
  repository: http://github.com/reneeb/MojoX-Renderer-HTC.git
version: '0.03'
