---
abstract: 'OpenAPI / Swagger plugin for Mojolicious'
author:
  - 'Jan Henning Thorsen <jhthorsen@cpan.org>'
build_requires:
  Test::More: '0.88'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.24, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-OpenAPI
no_index:
  directory:
    - t
    - inc
requires:
  JSON::Validator: '2.00'
  Mojolicious: '6.40'
resources:
  bugtracker: https://github.com/jhthorsen/mojolicious-plugin-openapi/issues
  homepage: https://github.com/jhthorsen/mojolicious-plugin-openapi
  repository: https://github.com/jhthorsen/mojolicious-plugin-openapi.git
version: '1.27'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
