---
abstract: 'Use Piwik in Mojolicious'
author:
  - 'Nils Diewald'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.32, CPAN::Meta::Converter version 2.150005'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-Piwik
no_index:
  directory:
    - t
    - inc
requires:
  Mojolicious: '4.88'
  perl: '5.010001'
resources:
  license: http://www.opensource.org/licenses/artistic-license-2.0
version: '0.20'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
