---
abstract: unknown
author:
  - 'Scott Wiersdorf <scott@perlcode.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.18, CPAN::Meta::Converter version 2.150005'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-Google-Cloud-UserAgent
no_index:
  directory:
    - t
    - inc
requires:
  Mojo::JWT::Google: '0.05'
  Mojolicious: '6.64'
version: '0.03'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
