---
abstract: 'Add some helpers to add and configure Devexpress controls'
author:
  - 'Nicolas Georges <xlat@cpan.org>'
build_requires:
  Cwd: '0'
  Mojolicious::Lite: '0'
  Pod::Coverage::TrustPod: '0'
  Test::Mojo: '0'
  Test::More: '0'
  perl: '5.010'
  warnings: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.036, CPAN::Meta::Converter version 2.142060'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-DevexpressHelpers
requires:
  Modern::Perl: '0'
  Mojo::Base: '0'
  Mojo::ByteStream: '0'
  MojoX::AlmostJSON: '0'
  Mojolicious::Plugin::AssetPack: '1.20'
  constant: '0'
  perl: '5.010'
  strict: '0'
  utf8: '0'
resources:
  repository: git://github.com/xlat/Mojolicious-Plugin-DevexpressHelpers.git
version: '0.163572'
