---
abstract: 'Provide NTLM authentication by forwarding requests to an upstram AD server'
author:
  - 'Tobias Oetiker <tobi@oetiker.ch>'
build_requires:
  CPAN::Uploader: '0'
  Pod::Markdown::Github: '0.01'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.0401, CPAN::Meta::Converter version 2.150001'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-SPNEGO
no_index:
  directory:
    - t
    - inc
    - t
    - eg
requires:
  Mojolicious: '7.01'
  Net::LDAP::SPNEGO: v0.1.4
  perl: '5.010001'
resources:
  bugtracker: https://github.com/oetiker/mojolicious-plugin-spnego/issues
  license: http://www.opensource.org/licenses/artistic-license-2.0
  repository: https://github.com/oetiker/mojolicious-plugin-spnego
version: v0.3.0
