---
abstract: 'Mojolicious ♥ PostgreSQL'
author:
  - 'Sebastian Riedel <sri@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.3, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojo-Pg
no_index:
  directory:
    - t
    - inc
    - examples
    - t
requires:
  DBD::Pg: '3.005001'
  Mojolicious: '7.53'
  SQL::Abstract: '1.85'
  perl: '5.010001'
resources:
  IRC: irc://irc.perl.org/#mojo
  bugtracker: https://github.com/kraih/mojo-pg/issues
  homepage: http://mojolicious.org
  license: http://www.opensource.org/licenses/artistic-license-2.0
  repository: https://github.com/kraih/mojo-pg.git
version: '4.08'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
