---
abstract: 'Some general helpers'
author:
  - 'Renee Baecker <reneeb@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.029, CPAN::Meta::Converter version 2.142060'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-MoreHTMLHelpers
requires:
  Mojolicious: '4.50'
resources:
  bugtracker: http://github.com/reneeb/Mojolicious-Plugin-MoreHTMLHelpers/issues
  homepage: http://github.com/reneeb/Mojolicious-Plugin-MoreHTMLHelpers
  repository: http://github.com/reneeb/Mojolicious-Plugin-MoreHTMLHelpers.git
version: '0.01'
