---
abstract: 'localize concise time duration string representation.'
author:
  - 'binary.com <BINARY@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::CheckDeps: '0.010'
  Test::Exception: '0'
  Test::FailWarnings: '0'
  Test::More: '0.94'
  Test::NoWarnings: '0'
  perl: '5.014000'
configure_requires:
  ExtUtils::MakeMaker: '6.48'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.007, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Time-Duration-Concise-Localize
requires:
  Carp: '0'
  Module::Pluggable: '0'
  POSIX: '0'
  Tie::Hash::LRU: '0'
  Time::Seconds: '1.27'
  perl: '5.014000'
resources:
  bugtracker: https://github.com/binary-com/perl-Time-Duration-Concise-Localize/issues
  repository: git://github.com/binary-com/perl-Time-Duration-Concise-Localize.git
version: '2.61'
x_serialization_backend: 'YAML::Tiny version 1.66'
