---
abstract: 'Simple Log::Dispatch replacement of Mojo::Log'
author:
  - 'Gryphon Shafer <gryphon@cpan.org>'
build_requires:
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Log::Dispatch: '0'
  Test::More: '0'
  Test::Most: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.037, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MojoX-Log-Dispatch-Simple
requires:
  Mojo::Base: '0'
  Mojo::Util: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/gryphonshafer/MojoX-Log-Dispatch-Simple/issues
  homepage: https://github.com/gryphonshafer/MojoX-Log-Dispatch-Simple
  repository: https://github.com/gryphonshafer/MojoX-Log-Dispatch-Simple.git
version: '1.05'
