---
abstract: 'Mojolicious plugin to load INI format config file'
author:
  - 'Yuki Kimoto <kimoto.yuki@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.04, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-INIConfig
no_index:
  directory:
    - t
    - inc
requires:
  Config::Tiny: '2.14'
  Mojolicious: '3.84'
version: '0.06'
x_serialization_backend: 'CPAN::Meta::YAML version 0.016'
