---
abstract: 'Mojolicious + http://materializecss.com/'
author:
  - 'mudler <mudler@dark-lab.net>'
build_requires:
  Mojolicious: '0'
  Test::Mojo: '0'
  Test::More: '0.98'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Minilla/v2.5.0, CPAN::Meta::Converter version 2.150001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-Materialize
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Mojolicious::Plugin::Materialize:
    file: lib/Mojolicious/Plugin/Materialize.pm
    version: '0.9770'
requires:
  Mojo::Base: '0'
  Mojolicious::Plugin::AssetPack: '0'
  Mojolicious::Plugin::AssetPack::Backcompat: '0'
  perl: '5.010001'
resources:
  bugtracker: https://github.com/mudler/Mojolicious-Plugin-Materialize/issues
  homepage: https://github.com/mudler/Mojolicious-Plugin-Materialize
  repository: git://github.com/mudler/Mojolicious-Plugin-Materialize.git
version: '0.9770'
x_authority: cpan:MUDLER
x_contributors:
  - 'mudler <mudler@sabayon.org>'
