---
abstract: 'Easily render rectangular data in many formats using Mojolicious'
author:
  - 'Joel Berger, E<lt>joel.a.berger@gmail.comE<gt>'
build_requires:
  Test::Without::Module: '0'
configure_requires:
  Module::Build::Tiny: '0.034'
dynamic_config: 0
generated_by: 'App::ModuleBuildTiny version 0.018, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-ReplyTable
provides:
  Mojolicious::Plugin::ReplyTable:
    file: lib/Mojolicious/Plugin/ReplyTable.pm
    version: '0.09'
recommends:
  Excel::Writer::XLSX: '0'
  Spreadsheet::WriteExcel: '0'
  Text::Table::Tiny: '0'
requires:
  Mojolicious: '5.60'
  Text::CSV: '0'
resources:
  bugtracker: http://github.com/jberger/Mojolicious-Plugin-ReplyTable/issues
  license: http://dev.perl.org/licenses/
  repository: http://github.com/jberger/Mojolicious-Plugin-ReplyTable
version: '0.09'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
