---
abstract: 'IOLoop interface to tail a file asynchronously'
author:
  - 'Brian Medley <bpmedley@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.039, CPAN::Meta::Converter version 2.150001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojo-IOLoop-Tail
requires:
  Mojolicious: '0'
version: '0.02'
