---
abstract: 'Easy Email sending with mailgun'
author:
  - 'Marcus Ramberg <marcus.ramberg@gmail.com>'
build_requires:
  Test::More: '0.88'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.24, CPAN::Meta::Converter version 2.150005'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-Mailgun
no_index:
  directory:
    - t
    - inc
requires:
  Mojolicious: '7.0'
  perl: v5.10.0
resources:
  bugtracker: https://github.com/marcus/mojolicious-plugin-mailgun/issues
  homepage: https://github.com/marcus/mojolicious-plugin-mailgun
  repository: https://github.com/marcusramberg/mojolicious-plugin-mailgun.git
version: '0.04'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
