---
abstract: 'Mojolicious Plugin for CSS theming'
author:
  - 'Kathryn Andersen <perlkat@katspace.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Module::Build: '0.3601'
  Test::More: '0'
  blib: '1.01'
  perl: '5.006'
  strict: '0'
  warnings: '0'
configure_requires:
  Module::Build: '0.3601'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.009, CPAN::Meta::Converter version 2.150001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-Foil
requires:
  Config::Context: '0'
  File::ShareDir: '0'
  File::Slurper: '0'
  HTML::LinkList: '0'
  Image::Size: '0'
  JSON::MaybeXS: '0'
  Mojo::Base: '0'
  Path::Tiny: '0'
  common::sense: '0'
resources:
  homepage: https://github.com/rubykat/mojolicious-plugin-foil
  repository: https://github.com/rubykat/mojolicious-plugin-foil.git
version: '0.006'
x_serialization_backend: 'YAML::Tiny version 1.70'
