---
abstract: 'Sendgrid API implementation for the Mojolicious framework'
author:
  - 'Stefan Adams <s1037989@gmail.com>'
build_requires:
  Test::More: '0.88'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.0401, CPAN::Meta::Converter version 2.150005'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojo-Sendgrid
no_index:
  directory:
    - t
    - inc
requires:
  Mojolicious: '6.00'
  perl: v5.14.0
resources:
  bugtracker: https://github.com/s1037989/Mojo-Sendgrid/issues
  homepage: https://github.com/s1037989/Mojo-Sendgrid
  repository: https://github.com/s1037989/Mojo-Sendgrid.git
version: '0.05'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
