---
abstract: 'Sentry client for Mojolicious'
author:
  - 'Adrian Crisan <adrian.crisan88@gmail.com>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.1, CPAN::Meta::Converter version 2.133380'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-GetSentry
no_index:
  directory:
    - t
    - inc
requires:
  Data::Dump: '0'
  Devel::StackTrace::Extract: '0'
  Mojo::IOLoop: '0'
  Sentry::Raven: '0'
  perl: '5.006'
version: v1.1.6
