---
abstract: 'Model for Mojolicious applications'
author:
  - 'Andrey Khozov, C<avkhozov@googlemail.com>.'
build_requires: {}
configure_requires:
  Module::Build::Tiny: '0.035'
dynamic_config: 0
generated_by: 'Minilla/v3.0.13, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-Model
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  MojoX::Model:
    file: lib/MojoX/Model.pm
  Mojolicious::Plugin::Model:
    file: lib/Mojolicious/Plugin/Model.pm
    version: '0.11'
requires:
  List::Util: '1.33'
  Mojolicious: '5.80'
  perl: '5.010001'
resources:
  bugtracker: https://github.com/avkhozov/Mojolicious-Plugin-Model/issues
  homepage: https://github.com/avkhozov/Mojolicious-Plugin-Model
  repository: git://github.com/avkhozov/Mojolicious-Plugin-Model.git
version: '0.11'
x_authority: cpan:AVKHOZOV
x_contributors:
  - 'Andrey Khozov <avkhozov@gmail.com>'
  - 'Denis Ibaev <dionys@gmail.com>'
  - 'Logioniz <logioniz@ya.ru>'
  - 'ccn <ccnweb@gmail.com>'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
