---
abstract: unknown
author:
  - 'Adrian Crisan <adrian.crisan88@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.1, CPAN::Meta::Converter version 2.133380'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-Validate-Tiny
no_index:
  directory:
    - t
    - inc
requires:
  Mojolicious: '6'
  Validate::Tiny: '0.984'
  perl: '5.01'
resources:
  repository: https://github.com/crlcu/Mojolicious-Plugin-Validate-Tiny
version: '0.17'
