---
abstract: 'Simple Twitter API client'
author:
  - 'Dan Book <dbook@cpan.org>'
build_requires:
  List::Util: '0'
  Test::More: '0.88'
configure_requires:
  Module::Build::Tiny: '0.034'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.043, CPAN::Meta::Converter version 2.150005'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojo-WebService-Twitter
no_index:
  directory:
    - eg
    - examples
    - inc
    - share
    - t
    - xt
provides:
  Mojo::WebService::Twitter:
    file: lib/Mojo/WebService/Twitter.pm
    version: '0.002'
  Mojo::WebService::Twitter::Error:
    file: lib/Mojo/WebService/Twitter/Error.pm
    version: '0.002'
  Mojo::WebService::Twitter::Tweet:
    file: lib/Mojo/WebService/Twitter/Tweet.pm
    version: '0.002'
  Mojo::WebService::Twitter::User:
    file: lib/Mojo/WebService/Twitter/User.pm
    version: '0.002'
  Mojo::WebService::Twitter::Util:
    file: lib/Mojo/WebService/Twitter/Util.pm
    version: '0.002'
requires:
  Carp: '0'
  Exporter: '0'
  IO::Socket::SSL: '1.94'
  Mojolicious: '6.0'
  Scalar::Util: '0'
  Time::Piece: '1.17'
  WWW::OAuth: '0'
  perl: '5.010001'
resources:
  bugtracker: https://github.com/Grinnz/Mojo-WebService-Twitter/issues
  homepage: https://github.com/Grinnz/Mojo-WebService-Twitter
  repository: https://github.com/Grinnz/Mojo-WebService-Twitter.git
version: '0.002'
x_contributors:
  - 'Dan Book <grinnz@grinnz.com>'
