---
abstract: 'Lazy load images'
author:
  - 'Jan Henning Thorsen <jhthorsen@cpan.org>'
build_requires:
  Test::More: '0.90'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.24, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-LazyImage
no_index:
  directory:
    - t
    - inc
requires:
  Mojolicious: '7.40'
resources:
  bugtracker: https://github.com/jhthorsen/mojolicious-plugin-lazyimage/issues
  homepage: https://github.com/jhthorsen/mojolicious-plugin-lazyimage
  repository: https://github.com/jhthorsen/mojolicious-plugin-lazyimage.git
version: '0.01'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
