---
abstract: 'The great new Mojolicious::Plugin::ExportExcel!'
author:
  - 'WFSO <461663376@qq.com>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.3, CPAN::Meta::Converter version 2.150010'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-ExportExcel
no_index:
  directory:
    - t
    - inc
requires:
  Mojolicious: '7.70'
  Spreadsheet::WriteExcel: '2.40'
  perl: '5.006'
version: v1.1.1
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
