---
abstract: 'Catalyst-like models in Mojolicious'
author:
  - 'Alexander Ruzhnikov.'
build_requires:
  File::Path: 0
  FindBin: 0
  Test::More: 0.98
configure_requires:
  Module::Build::Tiny: 0.035
dynamic_config: 0
generated_by: 'Minilla/v3.0.1, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-BModel
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Mojolicious::BModel::Base:
    file: lib/Mojolicious/BModel/Base.pm
    version: 0.09
  Mojolicious::Plugin::BModel:
    file: lib/Mojolicious/Plugin/BModel.pm
    version: 0.09
requires:
  Carp: 0
  File::Find: 0
  Mojo::Loader: 0
  Mojolicious: 6.0
  perl: 5.010
resources:
  bugtracker: https://github.com/ruzhnikov/Mojolicious-Plugin-BModel/issues
  homepage: https://github.com/ruzhnikov/Mojolicious-Plugin-BModel
  repository: git://github.com/ruzhnikov/Mojolicious-Plugin-BModel.git
version: 0.09
x_authority: cpan:BCDE
x_contributors:
  - 'Alexander Ruzhnikov <ruzhnikov85@gmail.com>'
