---
abstract: 'An AccessLog Plugin for Mojolicious'
author:
  - 'Bernhard Graf'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  IO::File: '0'
  Mojolicious: '3.28'
  POSIX: '0'
  Scalar::Util: '0'
  Socket: '0'
  Time::HiRes: '0'
  Time::Local: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.0401, CPAN::Meta::Converter version 2.150001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-AccessLog
no_index:
  directory:
    - t
    - inc
requires:
  File::Spec: '0'
  IO::File: '0'
  Mojolicious: '3.28'
  Scalar::Util: '0'
  Socket: '0'
  Time::HiRes: '0'
  perl: '5.010001'
resources:
  bugtracker: https://github.com/augensalat/mojolicious-plugin-accesslog/issues
  license: http://dev.perl.org/licenses/
  repository: https://github.com/augensalat/mojolicious-plugin-accesslog.git
version: '0.010'
