---
abstract: 'Sample Morbo Inotify watcher'
author:
  - 'Marcus Ramberg <marcus.ramberg@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.24, CPAN::Meta::Converter version 2.150005'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojo-Server-Morbo-Backend-Inotify
no_index:
  directory:
    - t
    - inc
requires:
  Linux::Inotify2: '0'
  Mojolicious: '7.31'
resources:
  bugtracker: https://github.com/marcusramberg/mojo-server-morbo-backend-inotify/issues
  homepage: https://github.com/marcusramberg/mojo-server-morbo-backend-inotify
  repository: https://github.com/marcusramberg/mojo-server-morbo-backend-inotify.git
version: '0.04'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
