---
abstract: 'Encapsulates the process for a Mojo app to send an expensive job to a daemon using Redis underneath and Redis SET NX and Redis Pub/Sub.'
author:
  - 'binary.com <BINARY@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::CheckDeps: '0.010'
  Test::More: '0.94'
  Test::Most: '0'
  perl: '5.014000'
configure_requires:
  ExtUtils::MakeMaker: '6.48'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.007, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojo-Redis-Processor
requires:
  Array::Utils: '0'
  JSON::XS: '0'
  Mojo::Redis2: '0'
  Parallel::ForkManager: '0'
  RedisDB: '0'
resources:
  bugtracker: https://github.com/binary-com/perl-Mojo-Redis-Processor/issues
  repository: git://github.com/binary-com/perl-Mojo-Redis-Processor.git
version: '0.07'
x_serialization_backend: 'YAML::Tiny version 1.66'
