---
abstract: 'Send captured placeholder values as parameters for routes.'
author:
  - 'Brian Duggan <bduggan@matatu.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.142690'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-AutoParams
no_index:
  directory:
    - t
    - inc
requires:
  Mojolicious: '5.0'
resources:
  repository: https://github.com/bduggan/Mojolicious-Plugin-AutoParams.git
version: '0.02'
