---
abstract: 'simple cloudflare client without wrapper'
author:
  - 'Fayland Lam <fayland@gmail.com>'
build_requires:
  Test::More: '0.96'
configure_requires:
  Module::Build::Tiny: '0.034'
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.18, Dist::Zilla version 6.010, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MojoX-CloudFlare-Simple
no_index:
  directory:
    - eg
    - examples
    - inc
    - share
    - t
    - xt
requires:
  Mojo::UserAgent: '0'
  perl: '5.008005'
resources:
  bugtracker: https://github.com/fayland/perl-MojoX-CloudFlare-Simple/issues
  homepage: https://github.com/fayland/perl-MojoX-CloudFlare-Simple
  repository: https://github.com/fayland/perl-MojoX-CloudFlare-Simple.git
version: '0.03'
x_serialization_backend: 'YAML::Tiny version 1.70'
