---
abstract: 'A Eeay crawler for html page!'
author:
  - 'ORANGE <bollwarm@ijz.me>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.16, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojo-Ecrawler
no_index:
  directory:
    - t
    - inc
requires:
  Mojolicious: '6.11'
  perl: '5.01'
resources:
  repository: https://git.oschina.net/ijz/Mojo-Zabbix
version: '0.04'
