---
abstract: 'Parse string that represents time duration'
author:
  - 'Tatsuhiko Miyagawa <miyagawa@bulknews.net>'
build_requires:
  Test::More: '0.88'
  Time::Duration: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.037, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Time-Duration-Parse
requires:
  Carp: '0'
  Exporter::Lite: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  homepage: https://github.com/neilb/Time-Duration-Parse
  repository: https://github.com/neilb/Time-Duration-Parse.git
version: '0.13'
