---
abstract: 'Threaded Replacement for Mojo::IOLoop::Subprocess'
author:
  - 'Thomas Kratz <tomk@cpan.org>'
build_requires:
  Test::More: '0.98'
configure_requires:
  Module::Build::Tiny: '0.035'
dynamic_config: 0
generated_by: 'Minilla/v3.0.13, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojo-IOLoop-Thread
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Mojo::IOLoop::Thread:
    file: lib/Mojo/IOLoop/Thread.pm
    version: '0.06'
requires:
  Mojolicious: '7.35'
  perl: '5.008001'
resources:
  bugtracker: https://github.com/tomk3003/mojo-ioloop-thread/issues
  homepage: https://github.com/tomk3003/mojo-ioloop-thread
  repository: git://github.com/tomk3003/mojo-ioloop-thread.git
version: '0.06'
x_contributors:
  - 'tomk3003 <ThomasKratz@web.de>'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
