---
abstract: 'A Mojolicious Plugin for RESTful HTTP Actions'
author:
  - 'Huo Linhe <huolinhe@berrygenomics.com>'
build_requires:
  Modern::Perl: '0'
  Module::Build: '0.28'
  Mojolicious::Lite: '0'
  Test::Mojo: '0'
  Test::More: '0'
  Test::Pod: '0'
  Test::Pod::Coverage: '1.00'
  lib: '0'
configure_requires:
  Module::Build: '0.28'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.037, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-RESTful
no_index:
  directory:
    - t
    - xt
    - inc
    - share
requires:
  Lingua::EN::Inflect: '0'
  List::Util: '0'
  Mojo::Base: '0'
  Mojo::Exception: '0'
  Mojo::Util: '0'
version: 0.1.4
