---
abstract: 'Mojolicious::Lite syntax in a full Mojolicious app.'
author:
  - 'Stefan Adams <stefan@borgia.com>'
build_requires:
  Test::More: '0.90'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.0401, CPAN::Meta::Converter version 2.150005'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-Mojolyst
no_index:
  directory:
    - t
    - inc
requires:
  ExtUtils::MakeMaker: '6.00'
  Mojolicious: '7.11'
  perl: '5.014'
resources:
  bugtracker: https://github.com/s1037989/Mojolicious-Plugin-Mojolyst/issues
  homepage: https://github.com/s1037989/Mojolicious-Plugin-Mojolyst
  repository: https://github.com/stefan/mojolicious-plugin-mojolyst
version: '0.01'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
