---
abstract: 'Like Mojo::IOLoop::Subprocess, spawns subprocesses with MCE::Hobo instead'
author:
  - 'Mario E. Roy <marioeroy AT gmail DOT com>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::More: '0.88'
  perl: '5.010001'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.010001'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.55_02, CPAN::Meta::Converter version 2.150001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojo-IOLoop-HoboProcess
no_index:
  directory:
    - t
    - inc
provides:
  Mojo::IOLoop::HoboProcess:
    file: lib/Mojo/IOLoop/HoboProcess.pm
    version: '0.005'
requires:
  Carp: '0'
  MCE::Shared: '1.817'
  Mojolicious: '7.07'
  Scalar::Util: '0'
  Socket: '0'
  perl: '5.010001'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/marioroy/Mojo-IOLoop-HoboProcess/issues
  homepage: https://github.com/marioroy/Mojo-IOLoop-HoboProcess
  license: http://dev.perl.org/licenses/
  repository: https://github.com/marioroy/Mojo-IOLoop-HoboProcess.git
version: '0.005'
