---
abstract: 'A SinaWeibo XiaoIce SDK and API'
author:
  - 'sjdy521 <sjdy521@163.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.1, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojo-SinaWeibo
no_index:
  directory:
    - t
    - inc
requires:
  Crypt::RSA: '0'
  Encode::Locale: '0'
  IO::Socket::SSL: '1.94'
  Mojolicious: '6.11'
resources: {}
version: '1.6'
x_serialization_backend: 'CPAN::Meta::YAML version 0.016'
