---
abstract: 'Compress and convert css, less, sass, javascript and coffeescript files'
author:
  - 'Jan Henning Thorsen <jhthorsen@cpan.org>'
build_requires:
  Test::More: '0.88'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.24, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-AssetPack
no_index:
  directory:
    - t
    - inc
requires:
  File::Which: '1.21'
  IPC::Run3: '0.048'
  Mojolicious: '7.17'
resources:
  bugtracker: https://github.com/jhthorsen/mojolicious-plugin-assetpack/issues
  homepage: https://github.com/jhthorsen/mojolicious-plugin-assetpack
  repository: https://github.com/jhthorsen/mojolicious-plugin-assetpack.git
version: '2.02'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
