---
abstract: 'Template Renderer Plugin for Mojolicious'
author:
  - 'Graham Ollis <plicease@cpan.org>'
build_requires:
  Test::More: '0.94'
  perl: '5.010001'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.010001'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.010, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-TtRenderer
no_index:
  directory:
    - example
recommends:
  EV: '0'
requires:
  Mojolicious: '6.33'
  POSIX: '0'
  Template: '2.18'
  Template::Provider: '0'
  perl: '5.010001'
resources:
  bugtracker: https://github.com/plicease/Mojolicious-Plugin-TtRenderer/issues
  homepage: https://metacpan.org/pod/Mojolicious::Plugin::TtRenderer
  repository: git://github.com/plicease/Mojolicious-Plugin-TtRenderer.git
version: '1.59'
x_contributors:
  - 'Ask Bjørn Hansen'
  - 'Graham Ollis <plicease@cpan.org>'
  - vti
  - 'Marcus Ramberg'
  - 'Matthias Bethke'
  - Htbaa
  - 'Magnus Holm'
  - 'Maxim Vuets'
  - 'Rafael Kitover'
  - giftnuss
  - 'Cosimo Streppone'
  - 'Fayland Lam'
  - 'Jason Crowther'
  - spleenjack
  - 'Árpád Szász'
  - 'Сергей Романов'
  - uwisser
  - 'Dinis Lage'
  - 'jay mortensen (GMORTEN)'
x_serialization_backend: 'YAML::Tiny version 1.70'
