---
abstract: 'readonly Chrome(MacOSx) cookies for Mojo::UserAgent'
author:
  - 'Fayland Lam <fayland@gmail.com>'
build_requires:
  Test::More: '0.96'
configure_requires:
  Module::Build::Tiny: '0.039'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.047, Dist::Milla version v1.0.15, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojo-UserAgent-CookieJar-ChromeMacOS
no_index:
  directory:
    - eg
    - examples
    - inc
    - share
    - t
    - xt
requires:
  Crypt::CBC: '0'
  Crypt::OpenSSL::AES: '0'
  DBD::SQLite: '0'
  DBI: '0'
  Mojolicious: '0'
  PBKDF2::Tiny: '0'
  perl: '5.010'
resources:
  bugtracker: https://github.com/fayland/perl-Mojo-UserAgent-CookieJar-ChromeMacOS/issues
  homepage: https://github.com/fayland/perl-Mojo-UserAgent-CookieJar-ChromeMacOS
  repository: https://github.com/fayland/perl-Mojo-UserAgent-CookieJar-ChromeMacOS.git
version: '0.01'
