---
abstract: 'Minimalistic integration of Mozillas "Persona" authentication system in Mojolicious apps'
author:
  - 'Heiko Jansen <hjansen@cpan.org>'
  - 'Moritz Lenz <moritz@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.031, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-MozPersona
requires:
  IO::Socket::SSL: '1.75'
  Mojolicious: '4.82'
  Mozilla::CA: '20141217'
resources:
  repository: https://github.com/heikojansen/mojolicious-plugin-mozpersona.git
version: '0.05'
