---
abstract: 'Mojolicious Plugin'
author:
  - 'Cyrill Novgorodcev <cynovg@cpan.org>'
build_requires: {}
configure_requires:
  Module::Build::Tiny: '0.035'
dynamic_config: 0
generated_by: 'Minilla/v3.0.10, CPAN::Meta::Converter version 2.142690'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-Template-Mustache
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Mojolicious::Plugin::Template::Mustache:
    file: lib/Mojolicious/Plugin/Template/Mustache.pm
    version: '0.03'
requires:
  Mojolicious: '0'
  Template::Mustache: v1.0.2
resources:
  bugtracker: https://github.com/cynovg/Mojolicious-Plugin-Template-Mustache/issues
  homepage: https://github.com/cynovg/Mojolicious-Plugin-Template-Mustache
  repository: git://github.com/cynovg/Mojolicious-Plugin-Template-Mustache.git
version: '0.03'
x_authority: cpan:CYNOVG
x_contributors:
  - 'Cyrill Novgorodcev <cynovg@gmail.com>'
  - 'Kirill Novgorodcev <novgorodtsev.kirill@220-volt.ru>'
