---
abstract: 'Convert a URL to embedded content'
author:
  - 'Jan Henning Thorsen <jhthorsen@cpan.org>'
build_requires:
  File::Find: '0'
  Module::Find: '0'
  Test::More: '0.90'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.143240'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-LinkEmbedder
no_index:
  directory:
    - t
    - inc
requires:
  Mojolicious: '5.00'
resources:
  bugtracker: https://github.com/jhthorsen/mojolicious-plugin-linkembedder/issues
  homepage: https://github.com/jhthorsen/mojolicious-plugin-linkembedder
  repository: https://github.com/jhthorsen/mojolicious-plugin-linkembedder.git
version: '0.2301'
