---
abstract: 'compare different parameter validation modules'
author:
  - 'Toby Inkster (TOBYINK) <tobyink@cpan.org>'
build_requires:
  Module::Runtime: '0'
  Test::Modern: '0.013'
configure_requires:
  ExtUtils::MakeMaker: '6.17'
dynamic_config: 0
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.024, CPAN::Meta::Converter version 2.150005'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Benchmark-Featureset-ParamCheck
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  Benchmark::Featureset::ParamCheck:
    file: lib/Benchmark/Featureset/ParamCheck.pm
    version: '0.004'
  Benchmark::Featureset::ParamCheck::Base:
    file: lib/Benchmark/Featureset/ParamCheck/Base.pm
    version: '0.004'
  Benchmark::Featureset::ParamCheck::Base::DataValidator:
    file: lib/Benchmark/Featureset/ParamCheck/Base/DataValidator.pm
    version: '0.004'
  Benchmark::Featureset::ParamCheck::Base::MXPV:
    file: lib/Benchmark/Featureset/ParamCheck/Base/MXPV.pm
    version: '0.004'
  Benchmark::Featureset::ParamCheck::Base::PV:
    file: lib/Benchmark/Featureset/ParamCheck/Base/PV.pm
    version: '0.004'
  Benchmark::Featureset::ParamCheck::Base::PVC:
    file: lib/Benchmark/Featureset/ParamCheck/Base/PVC.pm
    version: '0.004'
  Benchmark::Featureset::ParamCheck::Base::ParamsCheck:
    file: lib/Benchmark/Featureset/ParamCheck/Base/ParamsCheck.pm
    version: '0.004'
  Benchmark::Featureset::ParamCheck::Implementation::DataValidator::Moose:
    file: lib/Benchmark/Featureset/ParamCheck/Implementation/DataValidator/Moose.pm
    version: '0.004'
  Benchmark::Featureset::ParamCheck::Implementation::DataValidator::Mouse:
    file: lib/Benchmark/Featureset/ParamCheck/Implementation/DataValidator/Mouse.pm
    version: '0.004'
  Benchmark::Featureset::ParamCheck::Implementation::DataValidator::TypeTiny:
    file: lib/Benchmark/Featureset/ParamCheck/Implementation/DataValidator/TypeTiny.pm
    version: '0.004'
  Benchmark::Featureset::ParamCheck::Implementation::MXPV::Moose:
    file: lib/Benchmark/Featureset/ParamCheck/Implementation/MXPV/Moose.pm
    version: '0.004'
  Benchmark::Featureset::ParamCheck::Implementation::MXPV::TypeTiny:
    file: lib/Benchmark/Featureset/ParamCheck/Implementation/MXPV/TypeTiny.pm
    version: '0.004'
  Benchmark::Featureset::ParamCheck::Implementation::PV:
    file: lib/Benchmark/Featureset/ParamCheck/Implementation/PV.pm
    version: '0.004'
  Benchmark::Featureset::ParamCheck::Implementation::PV::TypeTiny:
    file: lib/Benchmark/Featureset/ParamCheck/Implementation/PV/TypeTiny.pm
    version: '0.004'
  Benchmark::Featureset::ParamCheck::Implementation::PVC::Moose:
    file: lib/Benchmark/Featureset/ParamCheck/Implementation/PVC/Moose.pm
    version: '0.004'
  Benchmark::Featureset::ParamCheck::Implementation::PVC::Specio:
    file: lib/Benchmark/Featureset/ParamCheck/Implementation/PVC/Specio.pm
    version: '0.004'
  Benchmark::Featureset::ParamCheck::Implementation::PVC::TypeTiny:
    file: lib/Benchmark/Featureset/ParamCheck/Implementation/PVC/TypeTiny.pm
    version: '0.004'
  Benchmark::Featureset::ParamCheck::Implementation::ParamsCheck::Perl:
    file: lib/Benchmark/Featureset/ParamCheck/Implementation/ParamsCheck/Perl.pm
    version: '0.004'
  Benchmark::Featureset::ParamCheck::Implementation::ParamsCheck::TypeTiny:
    file: lib/Benchmark/Featureset/ParamCheck/Implementation/ParamsCheck/TypeTiny.pm
    version: '0.004'
  Benchmark::Featureset::ParamCheck::Implementation::Perl:
    file: lib/Benchmark/Featureset/ParamCheck/Implementation/Perl.pm
    version: '0.004'
  Benchmark::Featureset::ParamCheck::Implementation::RefUtilXS:
    file: lib/Benchmark/Featureset/ParamCheck/Implementation/RefUtilXS.pm
    version: '0.004'
  Benchmark::Featureset::ParamCheck::Implementation::TypeParams:
    file: lib/Benchmark/Featureset/ParamCheck/Implementation/TypeParams.pm
    version: '0.004'
requires:
  Data::Validator: '1.07'
  IO::String: '0'
  Moose: '2.2002'
  Moose::Util::TypeConstraints: '2.2002'
  MooseX::Params::Validate: '0.21'
  Mouse: v2.4.7
  Mouse::Util::TypeConstraints: '0'
  Params::Check: '0.38'
  Params::Validate: '1.26'
  Params::ValidationCompiler: '0.24'
  Ref::Util: '0.203'
  Ref::Util::XS: '0.116'
  Specio::Declare: '0.37'
  Specio::Library::Builtins: '0.37'
  Type::Params: 1.001_009
  Type::Tiny::XS: '0.012'
  Types::Standard: 1.001_009
  namespace::autoclean: '0'
  perl: '5.012'
resources:
  Identifier: http://purl.org/NET/cpan-uri/dist/Benchmark-Featureset-ParamCheck/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Benchmark-Featureset-ParamCheck
  homepage: https://metacpan.org/release/Benchmark-Featureset-ParamCheck
  license: http://dev.perl.org/licenses/
  repository: git://github.com/tobyink/p5-benchmark-featureset-paramcheck.git
version: '0.004'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
x_static_install: 1
