---
abstract: 'Almost JSON but allow javascript function'
author:
  - 'Nicolas Georges <xlat@cpan.org>'
build_requires:
  Test::More: '0'
  strict: '0'
  warnings: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.036, CPAN::Meta::Converter version 2.142060'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MojoX-AlmostJSON
requires:
  B: '0'
  Carp: '0'
  Exporter: '0'
  Mojo::Base: '0'
  Mojo::Util: '0'
  Scalar::Util: '0'
  overload: '0'
version: '1.151250'
