---
abstract: 'Easier implementation of an OAuth2 Authorization Server / Resource Server with Mojolicious'
author:
  - 'Lee Johnson <leejo@cpan.org>'
build_requires:
  File::Find: '0'
  FindBin: '0'
  Test::Deep: '0.113'
  Test::Exception: '0.32'
  Test::Mojo: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.24, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-OAuth2-Server
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
  Mojolicious: '5.37'
  Net::OAuth2::AuthorizationServer: '0.17'
  perl: '5.010001'
resources:
  bugtracker: https://github.com/Humanstate/mojolicious-plugin-oauth2-server/issues
  homepage: https://metacpan.org/module/Mojolicious::Plugin::OAuth2::Server
  license: http://dev.perl.org/licenses/
  repository: https://github.com/Humanstate/mojolicious-plugin-oauth2-server
version: '0.41'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
