---
abstract: 'Mojolicious plugin validator for GET/POST data.'
author:
  - 'Dmitry E. Oboukhov <unera@debian.org>,'
  - 'Roman V. Nikolaev <rshadow@rambler.ru>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.24, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-Vparam
no_index:
  directory:
    - t
    - inc
requires:
  DateTime: '0'
  DateTime::Format::DateParse: '0'
  List::MoreUtils: '0'
  Mail::RFC822::Address: '0'
  Mojolicious: '0'
  Test::Compile: '0'
  Test::More: '0'
  XML::LibXML: '0'
  perl: '5.010000'
resources:
  bugtracker: https://github.com/dr-co/libmojolicious-plugin-vparam-perl/issues
  homepage: https://github.com/dr-co/libmojolicious-plugin-vparam-perl
  repository: https://github.com/dr-co/libmojolicious-plugin-vparam-perl
version: '3.06'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
